let valueInNumber = 123;
console.log("valueInNumber", valueInNumber, typeof valueInNumber);
let valueInString = String(valueInNumber);
console.log("valueInString", valueInString, typeof valueInString);
let valueInNumberAgain = Number(valueInString);
console.log("valueInNumberAgain", valueInNumberAgain, typeof valueInNumberAgain);
let booleanValue = true;
console.log("booleanValue", booleanValue, typeof booleanValue);
let booleanToString = String(booleanValue);
console.log("booleanToString", booleanToString, typeof booleanToString);
let stringToBoolean = Boolean(booleanToString);
console.log("stringToBoolean", stringToBoolean, typeof stringToBoolean);
let numberToBoolean = Boolean(valueInNumber);
console.log("numberToBoolean", numberToBoolean, typeof numberToBoolean);
let zeroToBoolean = Boolean(0);
console.log("zeroToBoolean", zeroToBoolean, typeof zeroToBoolean);
let emptyStringToBoolean = Boolean("");
console.log("emptyStringToBoolean", emptyStringToBoolean, typeof emptyStringToBoolean);
let nullToBoolean = Boolean(null);
console.log("nullToBoolean", nullToBoolean, typeof nullToBoolean);
let undefinedToBoolean = Boolean(undefined);
console.log("undefinedToBoolean", undefinedToBoolean, typeof undefinedToBoolean);
let NaNToBoolean = Boolean(NaN);
console.log("NaNToBoolean", NaNToBoolean, typeof NaNToBoolean);
let stringToNumber = Number("12345");
console.log("stringToNumber", stringToNumber, typeof stringToNumber);
let invalidStringToNumber = Number("12345abc");
console.log("invalidStringToNumber", invalidStringToNumber, typeof invalidStringToNumber);
let floatStringToNumber = Number("123.45");
console.log("floatStringToNumber", floatStringToNumber, typeof floatStringToNumber);
let booleanTrueToNumber = Number(true);
console.log("booleanTrueToNumber", booleanTrueToNumber, typeof booleanTrueToNumber);
let booleanFalseToNumber = Number(false);
console.log("booleanFalseToNumber", booleanFalseToNumber, typeof booleanFalseToNumber);
let nullToNumber = Number(null);
console.log("nullToNumber", nullToNumber, typeof nullToNumber);
let undefinedToNumber = Number(undefined);
console.log("undefinedToNumber", undefinedToNumber, typeof undefinedToNumber);
let NaNToNumber = Number(NaN);
console.log("NaNToNumber", NaNToNumber, typeof NaNToNumber);
let stringToFloat = parseFloat("123.456");
console.log("stringToFloat", stringToFloat, typeof stringToFloat);
let stringToInt = parseInt("123.456");
console.log("stringToInt", stringToInt, typeof stringToInt);
let floatToString = String(123.456);
console.log("floatToString", floatToString, typeof floatToString);
let intToString = String(123);
console.log("intToString", intToString, typeof intToString);
let numberToFloat = parseFloat(123);
console.log("numberToFloat", numberToFloat, typeof numberToFloat);
let numberToInt = parseInt(123.456);
console.log("numberToInt", numberToInt, typeof numberToInt);
let stringWithSpacesToNumber = Number("   12345   ");
console.log("stringWithSpacesToNumber", stringWithSpacesToNumber, typeof stringWithSpacesToNumber);
let stringWithSpacesToBoolean = Boolean("   ");
console.log("stringWithSpacesToBoolean", stringWithSpacesToBoolean, typeof stringWithSpacesToBoolean);
let emptyArrayToBoolean = Boolean([]);
console.log("emptyArrayToBoolean", emptyArrayToBoolean, typeof emptyArrayToBoolean);
let nonEmptyArrayToBoolean = Boolean([1, 2, 3]);
console.log("nonEmptyArrayToBoolean", nonEmptyArrayToBoolean, typeof nonEmptyArrayToBoolean);
let emptyObjectToBoolean = Boolean({});
console.log("emptyObjectToBoolean", emptyObjectToBoolean, typeof emptyObjectToBoolean);
let nonEmptyObjectToBoolean = Boolean({ key: "value" });
console.log("nonEmptyObjectToBoolean", nonEmptyObjectToBoolean, typeof nonEmptyObjectToBoolean);
let dateToString = String(new Date());
console.log("dateToString", dateToString, typeof dateToString);
let stringToDate = new Date("2024-01-01");
console.log("stringToDate", stringToDate, typeof stringToDate);
let numberToDate = new Date(1704067200000); // Timestamp for 2024-01-01
console.log("numberToDate", numberToDate, typeof numberToDate);
let invalidDate = new Date("invalid date string");
console.log("invalidDate", invalidDate, typeof invalidDate);